// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVZswkh3KFK38fpsdZACF6lSv_uSCYxHA',
    appId: '1:109957066564:web:8e2525fd3dd8db989c3111',
    messagingSenderId: '109957066564',
    projectId: 'algohunt',
    authDomain: 'algohunt.firebaseapp.com',
    storageBucket: 'algohunt.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdefnRVYhUkwFsvIo5okZxEOHSBSfnxO4',
    appId: '1:109957066564:android:e0e89054f5e141279c3111',
    messagingSenderId: '109957066564',
    projectId: 'algohunt',
    storageBucket: 'algohunt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp9ZhCNNqG57Vy3mr39bz2zCA5LIygnUk',
    appId: '1:109957066564:ios:e29cd11e4e0129df9c3111',
    messagingSenderId: '109957066564',
    projectId: 'algohunt',
    storageBucket: 'algohunt.appspot.com',
    iosBundleId: 'com.example.algohunt',
  );
}
